import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MenualHeader from "../components/MenualHeader";
import Header from "../components/Header";
import LotterEntrance from "../components/LotteryEntrance";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <MenualHeader></MenualHeader> */}
      <Header></Header>
      <LotterEntrance></LotterEntrance>
    </div>
  );
}
